---
language: python

python:
  - "3.8"

cache: pip

services:
  - docker

env:
  - MOLECULE_DISTRO=centos7
  # - MOLECULE_DISTRO=ubuntu1804
  # - MOLECULE_DISTRO=ubuntu1604
  - MOLECULE_DISTRO=debian9
  # - MOLECULE_DISTRO=debian10

install:
  - pip install --quiet yamllint
  - pip install --quiet ansible
  - pip install --quiet molecule
  - pip install --quiet 'molecule[docker]'
  - pip install --quiet ansible-lint
  - pip install --quiet flake8

before_script:
  - molecule --version
  - ansible --version

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
