---
- name: "Install SonarQube plugins"
  block:
    - name: "Set current plugin's jar filename"
      set_fact:
        current_plugin_jar_file: "{{ item.name }}-{{ item.version }}.jar"

    - name: "Set current plugins's custom download URL if available"
      set_fact:
        current_plugin_url: item.url
      when: item.url is defined and item.url | length > 0

    - name: "Set current plugins's default download URL no custom one"
      set_fact:
        current_plugin_url: "{{ item.commercial ? sonar_commercial_plugin_baseurl : sonar_plugin_baseurl }}/{{ item.name }}/{{ current_plugin_jar_file }}"
      when: current_plugin_url is not defined or current_plugin_url | length <= 0

    - name: "Download current plugin"
      get_url:
        url: "{{ current_plugin_url }}"
        dest: "{{ __sonar_plugin_home }}/{{ current_plugin_jar_file }}"
        owner: "{{ sonar_user }}"
        group: "{{ sonar_group }}"
      retries: 5
      delay: 10
  with_items: "{{ sonar_plugins }}"
  notify:
    - "restart SonarQube service"
