---
# starts after idempotence stage
- name: Side Effect
  hosts: all
  vars:
    sonar_version: 8.9.3.48735
    sonar_plugins: []
  tasks:
    - name: "Start role again and apply upgrade to {{ sonar_version }}"
      include_role:
        name: ansible-role-sonarqube
