---
# side_effect playbook from https://molecule.readthedocs.io/en/latest/configuration.html
# We use default test_sequence so Molecule initialize this playbook after the idempotence check

- name: Side Effect
  hosts: all
  vars:
    sonar_version: 7.4
    sonar_plugins: []
  tasks:
    - name: "Start role again and apply upgrade to {{ sonar_version }}"
      include_role:
        name: ansible-role-sonarqube
